default: &default
  adapter: postgresql
  encoding: utf-8
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: pecunia_development
  username: postgres
  password: postgres
  host: localhost
test:
  <<: *development
  database: pecunia_test
production:
  <<: *default
  database: pecunia_production
  username: pecunia
  password: <%= ENV["PECUNIA_DATABASE_PASSWORD"] %>
